config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pieces
  resources :portfolios

  resources :users

  root "users#index"
end

app/models/piece.rb
class Piece < ActiveRecord::Base
  belongs_to :portfolio

  has_attached_file :image, :styles => { :full => "1200x1200#", :medium => "300x300#", :thumb => "100x100#" }#, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  has_many :pieces

  has_attached_file :image, :styles => { :full => "1200x1200#", :medium => "300x300#", :thumb => "100x100#" }#, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :full => "1200x1200#", :medium => "300x300#", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def portfolios
    @portfolios = Portfolio.all
    @pieces = Piece.all
  end

  def pieces
    @portfolios = Portfolio.all
    @pieces = Piece.all
  end

  def artists
    @portfolios = Portfolio.all
    @pieces = Piece.all
  end

end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  before_action :find_piece, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @pieces = Piece.where(:user_id => current_user.id)
  end

  def show
  end

  def new
    @piece = Piece.new
    @portfolios = Portfolio.where(:user_id => current_user.id).order("title ASC")
  end

  def create
    @piece = Piece.new(piece_params)
    @piece.user_id = current_user.id
    if @piece.save
      redirect_to@piece, notice: "create successfully!"
    else
      render 'new'
    end
  end

  def edit
  end
  def update
    if @piece.update(piece_params)
      redirect_to@piece, notice: "saved successfully!"
    else
      render 'new'
    end
  end

  def destroy
    @piece.destroy
    redirect_to root_path
  end

  private
    def piece_params
      params.require(:piece).permit(:title, :created, :description, :image, :portfolio_id)
    end

    def find_piece
      @piece = Piece.find(params[:id])
      @portfolios = Portfolio.order("title ASC")
    end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :find_portfolio, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @portfolios = Portfolio.where(:user_id => current_user.id)
  end

  def show
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)
    @portfolio.user_id = current_user.id
    if @portfolio.save
      redirect_to @portfolio, notice: "create successfully!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @portfolio.update(portfolio_params)
      redirect_to @portfolio, notice: "saved successfully!"
    else
      render 'new'
    end
  end

  def destroy
    @portfolio.destroy
    redirect_to root_path
  end

  private
    def portfolio_params
      params.require(:portfolio).permit(:title, :created, :description, :image)
    end

    def find_portfolio
      @portfolio = Portfolio.find(params[:id])
      @pieces = @portfolio.pieces
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
      @users = User.all
  end

  def show
      @user = User.find(params[:id])
      @portfolios = Portfolio.where(:user_id => @user.id)
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(post_params)
      redirect_to user_path
    else
      render 'edit'
    end
  end

  private

  def post_params
    params.require(:user).permit(:name, :about, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= stylesheet_link_tag    'application', 'http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="navbar">

    <div id="logo">
      <%= link_to root_path do %>
        <%= image_tag "logo-new.png" %>
      <% end %>
    </div>

    <div id="navigation">
      <div class="nav_item"><%= link_to "Home", root_path %></div>
      <div class="nav_item"><%= link_to "About", root_path %></div>
      <div class="nav_item"><%= link_to "Blog", root_path %></div>
      <div class="nav_item"><%= link_to "Portfolio", root_path %></div>
      <div class="nav_item"><%= link_to "Shop", root_path %></div>
      <% if user_signed_in? %>
        <div class="nav_item"><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %> </div>
      <% else %>
        <div class="nav_item"><%= link_to('Sign in', new_user_session_path)  %></div>
      <% end %>
    </div>

  </div>


  <% if user_signed_in? %>
  <div id="loggedin_nav">
      <span class="user_name"><%= current_user.name.nil? ? current_user.email.split('@')[0].capitalize : current_user.name %>'s Dashboard</span>
      <div class="navigation">
        <div class="nav_item"><%= link_to "My Portfolios", portfolios_path %> </div>
        <div class="nav_item"><%= link_to "My Pieces", pieces_path %> </div>
        <div class="nav_item"><%= link_to 'Settings', user_path(current_user) %></div>
      </div>
  </div>
  <% end %>



<div id="main_content">
  <% flash.each do |name, msg| %>
    <div class="message">
     <%= content_tag(:div, msg, class: "alert") %>
   </div>
  <% end %>

  <%= yield %>
</div>
  <div id="footer">

      <div id="copyright">Skyler Layne, 2015</div>
    <div class="social">
      <span><a href="https://twitter.com/skylerto"> <%= image_tag "sm/twitter.png", :class => "social_media" %> </a></span>
      <span><a href="https://github.com/skylerto"><%= image_tag "sm/github.png", :class => "social_media" %> </a></span>
      <span><a href="mailto:skylerclayne@gmail.com"><%= image_tag "sm/mail.png", :class => "social_media" %> </a></span>
    </div>
  </div>

</body>
</html>

app/views/pages/portfolios.html.erb
<h1>Portfolios</h1>

<%= render "portfolios/portfolios" %>
<div class="clearfix">

</div>

app/views/partials/_buttons.html.erb
<% if defined?(edit_delete) && edit_delete == true %>
  <% if user_signed_in? && current_user.id == item.user_id %>
    <div class="buttons">
      <div class="button"><%= link_to 'Edit', "/#{item.class.to_s.downcase}s/#{item.id}/edit/" %></div>
      <div class="button"><%= link_to 'Delete', portfolio_path(item), method: :delete, data: { confirm: 'Are you sure?'} %></div>
    </div>
  <% end %>
<% end %>

<% if defined?(new_button) && new_button == true %>
  <% if user_signed_in? %>
    <div class="buttons">
      <div class="button"><%= link_to "New #{item.capitalize}", "/#{item}s/new" %></div>
    </div>
  <% end %>
<% end %>

app/views/pieces/_form.html.erb
<%= form_for @piece do |f| %>
<% if @piece.errors.any? %>
  <h2><%= pluralize(@piece.errors.count, "error")%> prevented this post from saving</h2>
  <ul>
    <% @piece.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

  <p>
    <% if !@piece.image.url.nil? %>
      <p>Current Image</p>
      <%= image_tag(@piece.image.url(:full)) %>
    <% end %>
  </p>

  <p>
    <%= f.label :image, 'New Image'  %>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.label :title %>
    <br/>
    <%= f.text_field :title %>
  </p>
<p>
  <%= f.label :portfolio_id %>
  <%= f.select(:portfolio_id, @portfolios.map {|p|
    name_and_factor = "#{p.title}"
    [name_and_factor, p.id]}) %>
</p>


  <p>
    <%= f.label :created %>
    <%= f.date_field :created %>
  </p>

  <p>
    <%= f.label :description%>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/pieces/_piece.html.erb
<div class="piece">
  <div class="piece_image">
    <%= image_tag(@piece.image.url(:full)) %>
  </div>

  <h1 class="piece_title"><%= @piece.title %></h1>
  <p class="artist_name">by <%= User.find(@piece.user_id).name? ? User.find(@piece.user_id).name : User.find(@piece.user_id).email %></p>
  <div class="piece_created">
    <%= @piece.created.strftime("%B %d, %Y") if @piece.created? %>
  </div>

  <div class="piece_description">
    <%= @piece.description %>
  </div>


<%= render "partials/buttons", :edit_delete => true, :item => @piece %>

  <div class="button">
  <%= link_to "back", root_path %>
  </div>

</div>

app/views/pieces/_pieces.html.erb
<% @pieces.each do |piece| %>
    <%= link_to(piece) do %>
    <div class="piecelet">
      <div class="piece_image">
        <%= image_tag(piece.image.url(:full)) if piece.image? %>
      </div>

      <div class="piece_header">
        <h2 class="piece_title"><%= piece.title %></h2>
        <p class="artist_name">by <%= User.find(piece.user_id).name? ? User.find(piece.user_id).name : User.find(piece.user_id).email %></p>
        <div class="piece_created">
          <%= piece.created.strftime("%B %d, %Y") if piece.created? %>
        </div>
        <%= render "partials/buttons", :edit_delete => true, :item => piece %>
      </div>





      <div class="clearfix"></div>
    </div>
  <% end %>
<% end %>

app/views/pieces/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Piece</h1>

<%= render 'form' %>
</div>

app/views/pieces/index.html.erb
<div id="page_wrapper">
<div class="portfolio">
<h1>Pieces</h1>
<%= render "partials/buttons", :new_button => true, :item => "piece" %>

<%= render 'pieces' %>

<div class="clearfix">

</div>
</div>

app/views/pieces/new.html.erb
<div id="page_wrapper">
  <h1>New Piece</h1>
  <%= render 'form' %>
</div>

app/views/pieces/show.html.erb
<div id="page_wrapper">
  <div class="portfolio">
      <%= render "piece" %>
  </div>
</div>

app/views/portfolios/_form.html.erb
<%= form_for @portfolio do |f| %>
<% if @portfolio.errors.any? %>
  <h2><%= pluralize(@portfolio.errors.count, "error")%> prevented this post from saving</h2>
  <ul>
    <% @portfolio.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

  <p>
    <%= f.label :image, class: 'col-sm-2 control-label'  %>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :created %>
    <%= f.date_field :created %>
  </p>

  <p>
    <%= f.label :description%>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/portfolios/_portfolios.html.erb
<% @portfolios.each do |portfolio| %>
    <%= link_to(portfolio) do %>
    <div class="portfoliolet">
      <div class="portfolio_image">
        <%= image_tag(portfolio.image.url(:thumb)) if portfolio.image? %>
      </div>

      <h2 class="portfolio_title"><%= portfolio.title %></h2>
      <p class="artist_name">by <%= User.find(portfolio.user_id).name? ? User.find(portfolio.user_id).name : User.find(portfolio.user_id).email %></p>
      <div class="portfolio_created">
        <%= portfolio.created.strftime("%B %d, %Y") %>
      </div>

      <div class="portfoliolet_description">
        <%= portfolio.description[0..100] + "..." %>
      </div>

    <%= render "partials/buttons", :edit_delete => true, :item => portfolio %>

    </div>
  <% end %>
<% end %>

app/views/portfolios/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Portfolio</h1>

<%= render 'form' %>
</div>

app/views/portfolios/index.html.erb
<h1>Portfolios</h1>
<%= render "partials/buttons", :new_button => true, :item => "portfolio" %>
<%= render "portfolios" %>
<div class="clearfix"></div>

app/views/portfolios/new.html.erb
<div id="page_wrapper">
  <h1>New Portfolio</h1>
  <%= render 'form' %>
</div>

app/views/portfolios/show.html.erb
<div id="page_wrapper">



<div class="portfolio">
  <div class="portfolio_image">
    <%= image_tag(@portfolio.image.url(:medium)) %>
  </div>

  <h1 class="portfolio_title"><%= @portfolio.title %></h1>
  <div class="portfolio_created">
    <%= @portfolio.created.strftime("%B %d, %Y") %>
  </div>

  <div class="portfolio_description">
    <%= @portfolio.description %>
  </div>

<%= render "pieces/pieces" %>
  <div class="clearfix">

  </div>

  <div class="button">
  <%= link_to "back", root_path %>
  </div>

</div>

</div>

app/views/users/_artists.html.erb
<% @users.each do |user| %>

    <div class="piecelet">
      <%= link_to(user) do %>
      <div class="piece_image">
        <%= image_tag(user.avatar.url(:full)) if user.avatar? %>
      </div>

      <div class="piece_header">
        <p class="artist"><%= user.name? ? user.name : user.email %></p>


      </div>

        <div class="clearfix"></div>

    </div>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, multipart: true do |f| %>
<% if @user.errors.any? %>
  <h2><%= pluralize(@post.errors.count, "error")%> prevented this post from saving</h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<p>

    <%= f.label :avatar %>
</p>
<p>

  <% if not current_user.avatar.nil? %>
    <%= image_tag(current_user.avatar.url(:thumb)) %>
  <% end %>
  <br/>
  <%= f.file_field :avatar %>
</p>

  <p>
    <%= f.label :name %> </br>
    <%= f.text_field :name %> </br>
  </p>


    <p>
      <%= f.label :about %> </br>
      <%= f.text_area :about %> </br>
    </p>


  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Change Password or Email address", edit_user_registration_path %>

app/views/users/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Profile</h1>

<%= render 'form' %>
</div>

app/views/users/index.html.erb
<h1>Artists</h1>
<%= render "artists" %>
<div class="clearfix"></div>

app/views/users/shared/_links.html.erb
<p style="padding">


<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>
</p>

app/views/users/show.html.erb
  <div id="page_wrapper">
    <!-- PROFILE PICTURE
     <div id="profile_image">
      <%= image_tag "profile.jpg" %>
    </div> -->
    <div id="main_content">
      <div id="profile_image">
        <%= image_tag(@user.avatar.url(:medium), :class => "profile") %>
      </div>
      <% if @user.name? %>
        <p>Name: <%= @user.name %></p>
      <% end %>
      <p>Username: <%= @user.email %></p>
      <% if @user.about? %>
        <p>
          <%= @user.about %>
        </p>
      <% end %>

      <% if user_signed_in? && @user.id == current_user.id %>
      <div class="buttons">
        <span class="button"><%= link_to "Edit", edit_user_path(current_user) %> </span>
      </div>
      <% end %>
      <div class="clearfix"></div>




      <div class="">

        <h1>Portfolios</h1>

        <%= render 'portfolios/portfolios' %>
      </div>



      <div class="clearfix"></div>


  </div>
  </div>